-- MySQL Script generated by MySQL Workbench
-- 09/27/15 14:45:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema widget-o
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `page`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `page` ;

CREATE TABLE IF NOT EXISTS `page` (
  `idpage` VARCHAR(32) NOT NULL COMMENT '',
  `template` VARCHAR(45) NOT NULL COMMENT '',
  `json` TEXT NOT NULL COMMENT '',
  PRIMARY KEY (`idpage`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `username` VARCHAR(45) NOT NULL COMMENT '',
  `password` CHAR(32) NOT NULL COMMENT '',
  PRIMARY KEY (`username`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oauth`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oauth` ;

CREATE TABLE IF NOT EXISTS `oauth` (
  `username` VARCHAR(45) NOT NULL COMMENT '',
  `token` CHAR(32) NOT NULL COMMENT '',
  PRIMARY KEY (`username`)  COMMENT '',
  CONSTRAINT `fk_oauthuser`
    FOREIGN KEY (`username`)
    REFERENCES `user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `page`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `page` (`idpage`, `template`, `json`) VALUES ('index.html', 'index.html', '{\"title\":{ \"text\": \"Welcome\"}}');

COMMIT;


-- -----------------------------------------------------
-- Data for table `user`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `user` (`username`, `password`) VALUES ('admin', '15691dbe02116508ae2150c1c8f24da9');

COMMIT;

