-- MySQL Script generated by MySQL Workbench
-- 10/25/15 19:48:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema widget-o
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
  `username` VARCHAR(45) NOT NULL COMMENT '',
  `password` CHAR(32) NOT NULL COMMENT '',
  PRIMARY KEY (`username`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `oauth`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oauth` (
  `username` VARCHAR(45) NOT NULL COMMENT '',
  `token` CHAR(32) NOT NULL COMMENT '',
  PRIMARY KEY (`username`)  COMMENT '',
  CONSTRAINT `fk_oauthuser`
    FOREIGN KEY (`username`)
    REFERENCES `user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `page`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `page` (
  `idpage` VARCHAR(32) NOT NULL COMMENT '',
  `template` VARCHAR(45) NOT NULL COMMENT '',
  `json` TEXT NOT NULL COMMENT '',
  PRIMARY KEY (`idpage`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `panel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `panel` (
  `idpanel` VARCHAR(128) NOT NULL COMMENT '',
  `json` TEXT NOT NULL COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `user`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `user` (`username`, `password`) VALUES ('admin', '5f4dcc3b5aa765d61d8327deb882cf99');

COMMIT;


-- -----------------------------------------------------
-- Data for table `page`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `page` (`idpage`, `template`, `json`) VALUES ('index.html', 'index.html', '{}');

COMMIT;

